import math

WIDTH = 1280 // 2
HEIGHT = 720 // 2
LOBBY_WIDTH = 1280
LOBBY_HEIGHT = 720
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
TILE = 100
FOV = math.pi / 3
HALF_FOV = FOV / 2

DIST = WIDTH / (2 * math.tan(HALF_WIDTH))
PR_CF = 3 * DIST * TILE
DOUBLE_PI = math.pi * 2
DELTA_ANGLE = FOV / WIDTH
CENTRAL_RAY = WIDTH // 2 - 1

FAKE_RAYS = 100
SCALE = WIDTH // WIDTH